name: release

on:
  workflow_dispatch:
  push:
    tags:
      - "v0.*"

jobs:
  Build:
    name: build-binary
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Hello world
        run: |
          cd server && go mod tidy
          uname -a
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: 'server/go.sum'

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: 'web/yarn.lock'

      - # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Build
        run: |
          mkdir server/ui
          touch server/ui/index.html
          #sudo apt-get install -y -q gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          bash release.sh

#  Docker:
#    name: build-docker
